Script started on 2016年03月14日 (週一) 17時56分21秒
]0;F74044046@2015cpp: ~/lab1F74044046@2015cpp:~/lab1$ git clone https://github.com/Fader1997/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwdgit push -u lab1 master[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K./lab1
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;F74044046@2015cpp: ~/lab1F74044046@2015cpp:~/lab1$ exit

Script done on 2016年03月14日 (週一) 18時00分34秒
